/**
 * Writes `BUG_REPORT.json` and `BUG_REPORT.md` — the developer deliverable.
 *
 * These are gitignored generated artifacts (see `.gitignore`). This diverges from
 * the API bench, which commits its `BUG_REPORT.*`: there the report is the artefact
 * under review, here it is regenerated whole by every run and handed over per run,
 * so committing it produces diff churn and a file that is stale between runs.
 *
 * `BUG_REPORT.json` carries the same field names the API bench uses — `generatedAt`,
 * `environment`, `baseURL`, `run`, `summary`, `defects[]` — so a consumer that reads
 * one bench's report can read the other's. The defect objects satisfy the QA
 * Dashboard's ingest contract (`QA-Dashboard/src/lib/validation.ts`) field for field,
 * which is what lets the pushed payload be a projection of this file rather than a
 * separately-assembled document that could drift from it.
 *
 * Both files are regenerated whole on every run. Nothing appends, so a shrinking
 * report means the defects really did go away.
 */
import fs from 'fs';
import path from 'path';
import {
  type RunModel,
  type UnattributedFailure,
  passRate,
  severityRank,
  verdict,
} from './run-model';

const ROOT = path.resolve(__dirname, '..', '..');

export interface WrittenReports {
  readonly json: string;
  readonly markdown: string;
}

export function writeBugReport(model: RunModel, root = ROOT): WrittenReports {
  const jsonPath = path.join(root, 'BUG_REPORT.json');
  const markdownPath = path.join(root, 'BUG_REPORT.md');

  fs.writeFileSync(jsonPath, `${JSON.stringify(model, null, 2)}\n`, 'utf-8');
  fs.writeFileSync(markdownPath, renderMarkdown(model), 'utf-8');

  return { json: jsonPath, markdown: markdownPath };
}

function renderMarkdown(model: RunModel): string {
  const lines: string[] = [
    '# KPost UI — Automated Bug Report',
    '',
    `> Generated by the KPost UI Test Bench on ${model.generatedAtHuman}.`,
    '> **This file is generated — do not edit by hand.** Re-run `npm test` to regenerate.',
    '',
  ];

  // The banner goes above everything. A reader who stops after one screen must not
  // walk away with a pass rate from a run that never finished.
  if (model.run.incomplete) {
    lines.push(
      '## ⚠ INCOMPLETE RUN',
      '',
      `**${verdict(model)}**`,
      '',
      ...model.run.incompleteReasons.map((reason) => `- ${reason}`),
      '',
      'The counts below are reported exactly as observed — they are NOT scaled up to the',
      'planned total. Treat this run as evidence about the tests that ran and about the',
      'truncation itself, and nothing more.',
      '',
    );
  }

  lines.push(
    '## Executive Summary',
    '',
    '| Metric | Value |',
    '| --- | --- |',
    `| Report generated | ${model.generatedAtHuman} |`,
    `| Environment | ${model.environment} |`,
    `| Target | \`${model.baseURL}\` |`,
    `| Browser projects | ${model.run.projects.join(', ') || '—'} |`,
    `| Tests planned | ${model.run.totalTests} |`,
    `| Reached a result | ${model.run.accounted} |`,
    `| Passed / Failed / Skipped | ${model.run.passed} / ${model.run.failed} / ${model.run.skipped} |`,
    ...(model.run.interrupted > 0 ? [`| Interrupted mid-flight | ${model.run.interrupted} |`] : []),
    ...(model.run.unaccounted > 0 ? [`| Never reached a result | ${model.run.unaccounted} |`] : []),
    `| Pass rate (of tests that ran) | ${formatPassRate(model)} |`,
    `| Run duration | ${model.run.durationSeconds}s |`,
    `| Playwright verdict | ${model.run.status} |`,
    '',
    '### Verdict',
    '',
    `**${verdict(model)}**`,
    '',
  );

  if (model.defects.length === 0) {
    lines.push(
      '### Known application defects observed',
      '',
      'None. No test in this run attached a `known-app-defect` annotation.',
      '',
      ...(model.run.incomplete
        ? [
            'Note: on a truncated run this means "none were reached", not "none exist" —',
            'most of the suite never executed.',
            '',
          ]
        : []),
    );
    return `${lines.join('\n')}\n`;
  }

  lines.push(
    '### Defect counts by severity',
    '',
    '| Severity | Count |',
    '| --- | --- |',
    ...Object.entries(model.summary.bySeverity)
      .sort(([a], [b]) => severityRank(a) - severityRank(b))
      .map(([severity, count]) => `| ${severity} | ${count} |`),
    `| **Total distinct defects** | **${model.summary.total}** |`,
    '',
    '### Defects by module',
    '',
    '| Module | Defects |',
    '| --- | --- |',
    ...Object.entries(model.summary.byModule)
      .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
      .map(([module, count]) => `| ${module} | ${count} |`),
    '',
    '### Defect index',
    '',
    '| ID | Severity | Module | Bugzilla | Title |',
    '| --- | --- | --- | --- | --- |',
    ...model.defects.map(
      (defect) =>
        `| ${defect.displayId} | ${defect.severity} | ${defect.module} | ` +
        `${defect.bugzillaId ? `[#${defect.bugzillaId}](${defect.bugzillaUrl})` : '—'} | ` +
        `${escapePipes(defect.title)} |`,
    ),
    '',
    '---',
    '',
    '## Defect detail',
    '',
  );

  for (const defect of model.defects) {
    lines.push(
      `### ${defect.displayId} — ${defect.title}`,
      '',
      `- **Severity:** ${defect.severity} · **Priority:** ${defect.priority} · **Category:** ${defect.category}`,
      `- **Module:** ${defect.module}`,
      `- **Owner:** ${defect.owner}`,
      // Present only when this run actually filed (or found) the ticket, so the
      // report never claims a bug number that does not exist.
      ...(defect.bugzillaId
        ? [`- **Bugzilla:** [bug #${defect.bugzillaId}](${defect.bugzillaUrl})`]
        : []),
      '',
      '**Evidence**',
      '',
      defect.description,
      '',
      '**Expected**',
      '',
      defect.expected,
      '',
      '**Observed in this run**',
      '',
      defect.actual,
      '',
      '**Browsers affected**',
      '',
      '| Browser | Tests that saw it |',
      '| --- | --- |',
      ...Object.entries(defect.browsers)
        .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
        .map(([browser, count]) => `| \`${browser}\` | ${count} |`),
      '',
      ...Object.entries(defect.sightingsByBrowser)
        .sort(([a], [b]) => a.localeCompare(b))
        .flatMap(([browser, titles]) => [
          `_${browser}_:`,
          ...titles.map((title) => `- ${escapePipes(title)}`),
          '',
        ]),
      '---',
      '',
    );
  }

  lines.push(...renderUnattributed(model));

  lines.push(
    '_These are **application** defects confirmed against the live app, registered in',
    '`src/utils/known-defects.ts`. The registry documents a defect; it never suppresses',
    'one — no assertion is weakened to accommodate an entry here. A test that observes a',
    'defect usually FAILS, because it asserts the behaviour the app should have; a few',
    'PASS because they pin the broken behaviour as a contract and are designed to turn red',
    'the day the app changes. "Observed in this run" above records which tests saw each',
    'defect and with what outcome. Full traces, screenshots and video: `npm run report`._',
  );

  return `${lines.join('\n')}\n`;
}

/**
 * The failures no defect explains.
 *
 * This section is what makes the defect count checkable. "191 failed, 17
 * defects" invites the obvious question — what about the other 174? — and the
 * answer is only trustworthy if the report shows its own residue instead of
 * leaving the reader to work it out. An empty residue is stated explicitly too:
 * "every failure is accounted for" is a claim worth making out loud.
 */
function renderUnattributed(model: RunModel): string[] {
  const orphans = model.run.unattributedFailures;
  if (model.run.failed === 0) return [];

  if (orphans.length === 0) {
    return [
      '## Failure accounting',
      '',
      `All **${model.run.failed}** failing test(s) are accounted for by the ` +
        `${model.summary.total} defect(s) above — none is unexplained.`,
      '',
      '---',
      '',
    ];
  }

  // Group by error text: unexplained failures usually share a handful of causes,
  // and a grouped list is a triage queue where a flat one is just a wall.
  const byCause = new Map<string, UnattributedFailure[]>();
  for (const failure of orphans) {
    const bucket = byCause.get(failure.error) ?? [];
    bucket.push(failure);
    byCause.set(failure.error, bucket);
  }

  return [
    '## ⚠ Failures with no registered defect',
    '',
    `**${orphans.length}** of this run's **${model.run.failed}** failing test(s) carry no entry ` +
      `from \`src/utils/known-defects.ts\`, so no ticket was filed for them. The other ` +
      `${model.run.failed - orphans.length} are explained by the ${model.summary.total} defect(s) above.`,
    '',
    'Each of these is either an application defect nobody has registered yet, or a test that ' +
      'needs fixing. Both need a human — that is why they are listed rather than counted.',
    '',
    ...[...byCause.entries()]
      .sort((a, b) => b[1].length - a[1].length)
      .flatMap(([cause, failures]) => [
        `### ${failures.length}× ${escapePipes(cause)}`,
        '',
        '| Browser | Spec | Test |',
        '| --- | --- | --- |',
        ...failures.map(
          (f) => `| \`${f.project}\` | \`${f.file}\` | ${escapePipes(f.testTitle)} |`,
        ),
        '',
      ]),
    '---',
    '',
  ];
}

function formatPassRate(model: RunModel): string {
  const rate = passRate(model);
  return rate === null ? 'n/a (no test produced a pass or fail)' : `${rate.toFixed(1)}%`;
}

/** Table cells break on a raw `|`; defect titles are free text. */
function escapePipes(text: string): string {
  return text.replace(/\|/g, '\\|');
}
